#!/usr/bin/env python3
"""Write db/seed.sql from db/cv.db — a plain-text backup of your experience.

    python3 db/dump_seed.py

`schema.sql` then `seed.sql` rebuilds the database exactly:

    sqlite3 fresh.db < db/schema.sql && sqlite3 fresh.db < db/seed.sql

Rows come out in primary-key order and every value is a literal, so re-running
this on an unchanged database produces a byte-identical file — the diff shows
what you actually edited, nothing else.

seed.sql is gitignored: it holds your name, phone, and email in plain text.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

HERE = Path(__file__).resolve().parent
DB = HERE / "cv.db"
OUT = HERE / "seed.sql"

# Insert order matters: parents before the rows that reference them.
TABLES = ["profile", "contact", "entry", "bullet", "skill", "entry_skill",
          "reference", "document", "section", "doc_entry", "doc_bullet",
          "doc_skill", "doc_reference", "version", "send"]

HEADER = """\
-- ============================================================================
--  cv_db — seed data
--  Generated by db/dump_seed.py. Edit the database through the form, not here.
--  Rebuild:  sqlite3 cv.db < schema.sql && sqlite3 cv.db < seed.sql
-- ============================================================================

PRAGMA foreign_keys = ON;
"""


def literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    lines = [HEADER]

    for table in TABLES:
        columns = [r[1] for r in con.execute(f"PRAGMA table_info({table})")]
        keys = {"entry_skill": "entry_id, skill_id",
                "doc_entry": "document_id, entry_id",
                "doc_bullet": "document_id, bullet_id",
                "doc_skill": "document_id, skill_id",
                "doc_reference": "document_id, reference_id"}
        order = keys.get(table, "id")
        rows = con.execute(f"SELECT * FROM {table} ORDER BY {order}").fetchall()
        if not rows:
            continue

        lines.append(f"\n-- {table} ({len(rows)} rows) " + "-" * max(0, 60 - len(table)))
        lines.append(f"INSERT INTO {table} ({', '.join(columns)}) VALUES")
        values = [f"({', '.join(literal(row[c]) for c in columns)})" for row in rows]
        lines.append(",\n".join(values) + ";")

    OUT.write_text("\n".join(lines) + "\n")
    con.close()
    print(f"wrote {OUT}  ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
