-- ============================================================================
--  cv_db — a blank CV
--  Loaded on top of schema.sql the first time you run the server. Gives you a
--  document with conventional headings so there is somewhere to put things,
--  and nothing else: no experience, no skills, no referees.
--
--  Rebuild from scratch:
--      rm db/cv.db && python3 server.py
--
--  Or start from the example CV in this repo instead:
--      rm db/cv.db && python3 server.py --seed example
-- ============================================================================

PRAGMA foreign_keys = ON;

-- The name at the top. Change it on the Profile tab — you do not edit this file.
INSERT INTO profile (id, full_name) VALUES (1, 'Your Name');

-- Headings in the order most CVs use them. Rename, reorder, or delete any of
-- them; they belong to this document and to nothing else.
--
--   entries     the full block, with bullets
--   itemized    one line each — the date, then what it was
--   skills      Category: a, b, c
--   references  a referee's details, stacked
--   profile     the paragraph from your profile
INSERT INTO document (id, slug, title, notes) VALUES
  (1, 'full-cv', 'Full CV', 'Everything. Copy it and cut it down for an application.');

INSERT INTO section (document_id, heading, style, sort_order) VALUES
  (1, 'Profile',       'profile',    1),
  (1, 'Education',     'entries',    2),
  (1, 'Experience',    'entries',    3),
  (1, 'Teaching',      'entries',    4),
  (1, 'Publications',  'itemized',   5),
  (1, 'Skills',        'skills',     6),
  (1, 'References',    'references', 7);
